import { CompetencyStandard, Student, ClinicalLog, CourseModule, VBONRegulation } from '@/types';

export const seedStudents: Student[] = [
  {
    id: 'S001',
    firstName: 'Sarah',
    lastName: 'Miller',
    cohort: 'Fall 2025',
    status: 'Active',
    clinicalHoursCompleted: 120,
    clinicalHoursRequired: 400,
    skillsCompleted: ['C001', 'C002'],
    nclexPredictorScore: 92,
    winProbability: 95,
    remediationStatus: 'Validated',
    remediationTopic: 'Phlebotomy',
    email: 'sarah.miller@pctc.edu',
    phone: '(540) 555-0123',
    dob: '2004-05-12',
    gpa: 3.8,
    notes: 'Exemplary clinical judgment. Aspires to work in ICU.',
    grades: [
      { id: 'GR1', studentId: 'S001', courseId: 'N101', courseName: 'Foundations of Nursing', grade: 94, semester: 'Fall 2024' },
      { id: 'GR2', studentId: 'S001', courseId: 'N102', courseName: 'Pharmacology I', grade: 88, semester: 'Fall 2024' },
    ]
  },
  {
    id: 'S002',
    firstName: 'James',
    lastName: 'Rodriguez',
    cohort: 'Fall 2025',
    status: 'At Risk',
    clinicalHoursCompleted: 90,
    clinicalHoursRequired: 400,
    skillsCompleted: ['C001'],
    nclexPredictorScore: 68,
    winProbability: 45,
    remediationStatus: 'Assigned',
    remediationTopic: 'Pharmacology Dosage Calc',
    email: 'j.rodriguez@pctc.edu',
    phone: '(540) 555-0145',
    dob: '2003-11-20',
    gpa: 2.7,
    notes: 'Struggling with dosage calculations. Needs more lab time.',
    grades: [
      { id: 'GR3', studentId: 'S002', courseId: 'N101', courseName: 'Foundations of Nursing', grade: 78, semester: 'Fall 2024' },
      { id: 'GR4', studentId: 'S002', courseId: 'N102', courseName: 'Pharmacology I', grade: 65, semester: 'Spring 2025' },
    ]
  },
  {
    id: 'S003',
    firstName: 'Emily',
    lastName: 'Chen',
    cohort: 'Fall 2025',
    status: 'Active',
    clinicalHoursCompleted: 135,
    clinicalHoursRequired: 400,
    skillsCompleted: ['C001', 'C002', 'C003'],
    nclexPredictorScore: 88,
    winProbability: 89,
    remediationStatus: 'None',
    email: 'emily.chen@pctc.edu',
    phone: '(540) 555-0167',
    dob: '2005-02-28',
    gpa: 3.5,
    notes: 'Strong interpersonal skills. Patient feedback is consistently positive.',
    grades: [
      { id: 'GR5', studentId: 'S003', courseId: 'N101', courseName: 'Foundations of Nursing', grade: 87, semester: 'Fall 2024' },
      { id: 'GR6', studentId: 'S003', courseId: 'N102', courseName: 'Pharmacology I', grade: 91, semester: 'Fall 2024' },
    ]
  },
];

export const seedStandards: CompetencyStandard[] = [
  {
    id: 'C001',
    code: 'VBON-18VAC90-27-100',
    category: 'VBON',
    description: 'Demonstrates safety in medication administration',
    effectiveDate: '2025-07-16',
  },
  {
    id: 'C002',
    code: 'NCLEX-PN-SE-1',
    category: 'NCLEX_PN',
    description: 'Safe and Effective Care Environment: Coordinated Care',
    effectiveDate: '2023-04-01',
  },
  {
    id: 'C003',
    code: 'NCLEX-PN-HP-2',
    category: 'NCLEX_PN',
    description: 'Health Promotion and Maintenance: Aging Process',
    effectiveDate: '2023-04-01',
  },
];

export const seedLogs: ClinicalLog[] = [
  {
    id: 'L001',
    studentId: 'S001',
    date: '2025-10-15',
    siteName: 'Page Memorial Hospital',
    patientDiagnosis: 'Congestive Heart Failure',
    mappedCompetencies: ['C001', 'C003'],
    status: 'Approved',
    hours: 8,
    isSimulation: false,
    isMakeup: false,
  },
  {
    id: 'L002',
    studentId: 'S002',
    date: '2025-10-15',
    siteName: 'Page Memorial Hospital',
    patientDiagnosis: 'Pneumonia',
    mappedCompetencies: ['C001'],
    status: 'Pending',
    instructorFeedback: 'Please provide more detail on respiratory assessment.',
    hours: 8,
    isSimulation: false,
    isMakeup: false,
  },
];

export const seedModules: CourseModule[] = [
  {
    id: 'M01',
    week: 1,
    title: 'Foundations of Nursing',
    description: 'Introduction to nursing roles, legal/ethical standards, and basic care.',
    mappedNclexCategories: ['C002'],
  },
  {
    id: 'M04',
    week: 4,
    title: 'Cardiovascular System',
    description: 'Anatomy, physiology, and common disorders of the heart.',
    mappedNclexCategories: ['C001'], // Simplified mapping
  },
];

export const seedEvents = [
  { id: 1, date: new Date(), title: 'Clinical Rotation: Med-Surg', type: 'clinical', location: 'Memorial Hospital - 3 South', proctor: 'Sarah Jenkins, RN', status: 'packet-sent' },
  { id: 2, date: new Date(), title: 'Pharm Exam 2', type: 'exam', location: 'Room 304', proctor: 'Dr. Smith', status: 'scheduled' },
  { id: 3, date: new Date(new Date().setDate(new Date().getDate() + 2)), title: 'Sim Lab: Cardiac', type: 'school', location: 'Simulation Center', proctor: 'Staff', status: 'scheduled' },
];

// VBON Regulations from Virginia Board of Nursing (18VAC90-27)
// Based on practical nursing education program requirements
export const seedVBONRegulations: VBONRegulation[] = [
  // Curriculum Content Requirements (Section B)
  {
    id: 'VBON-B1',
    code: 'B.1',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Adult Medical/Surgical Nursing',
    description: 'Evidence-based didactic content and supervised clinical practice in adult medical/surgical nursing including care of patients with acute and chronic conditions.',
    sortOrder: 1,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B2',
    code: 'B.2',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Nursing Process',
    description: 'Concepts of nursing process including assessment, diagnosis, planning, implementation, and evaluation of patient care.',
    sortOrder: 2,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B3',
    code: 'B.3',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Communication',
    description: 'Principles of therapeutic communication and interprofessional collaboration.',
    sortOrder: 3,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B4',
    code: 'B.4',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Legal/Ethical Standards',
    description: 'Legal and ethical standards of nursing practice, scope of practice, and professional accountability.',
    sortOrder: 4,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B5',
    code: 'B.5',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Safety & Infection Control',
    description: 'Principles of safety, infection control, standard precautions, and prevention of medical errors.',
    sortOrder: 5,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B6',
    code: 'B.6',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Pharmacology & Medication Administration',
    description: 'Pharmacology, dosage calculation, and safe medication administration including IV therapy basics.',
    sortOrder: 6,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B7',
    code: 'B.7',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Maternal/Newborn Nursing',
    description: 'Care of the childbearing family including prenatal, labor/delivery, postpartum, and newborn care.',
    sortOrder: 7,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B8',
    code: 'B.8',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Pediatric Nursing',
    description: 'Care of children from infancy through adolescence including growth, development, and common pediatric conditions.',
    sortOrder: 8,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B9',
    code: 'B.9',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Mental Health Nursing',
    description: 'Mental health concepts, therapeutic interventions, and care of patients with psychiatric conditions.',
    sortOrder: 9,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B10',
    code: 'B.10',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Gerontological Nursing',
    description: 'Care of the older adult including normal aging, common geriatric conditions, and end-of-life care.',
    sortOrder: 10,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B11',
    code: 'B.11',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Nutrition',
    description: 'Principles of nutrition, therapeutic diets, and nutritional assessment.',
    sortOrder: 11,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-B12',
    code: 'B.12',
    section: '18VAC90-27-100',
    category: 'Curriculum Content',
    title: 'Anatomy & Physiology',
    description: 'Basic anatomy and physiology as foundation for nursing care.',
    sortOrder: 12,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Clinical Requirements (Section C)
  {
    id: 'VBON-C1',
    code: 'C.1',
    section: '18VAC90-27-110',
    category: 'Clinical Requirements',
    title: 'Minimum Clinical Hours',
    description: 'Students shall complete a minimum number of supervised clinical hours as specified by the Board (minimum 400 hours for PN).',
    sortOrder: 13,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-C2',
    code: 'C.2',
    section: '18VAC90-27-110',
    category: 'Clinical Requirements',
    title: 'Simulation Hours Cap',
    description: 'Simulation may substitute for no more than 25% of total required clinical hours (maximum 100 hours for PN programs).',
    sortOrder: 14,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-C3',
    code: 'C.3',
    section: '18VAC90-27-110',
    category: 'Clinical Requirements',
    title: 'Direct Patient Care',
    description: 'Clinical experience must include direct patient care in a variety of healthcare settings.',
    sortOrder: 15,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-C4',
    code: 'C.4',
    section: '18VAC90-27-110',
    category: 'Clinical Requirements',
    title: 'Supervision Ratio',
    description: 'Faculty-to-student ratio shall not exceed 1:10 in clinical settings.',
    sortOrder: 16,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-C5',
    code: 'C.5',
    section: '18VAC90-27-110',
    category: 'Clinical Requirements',
    title: 'Preceptor Requirements',
    description: 'Preceptors must hold current RN licensure and meet program qualification requirements.',
    sortOrder: 17,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Faculty Requirements (Section D)
  {
    id: 'VBON-D1',
    code: 'D.1',
    section: '18VAC90-27-90',
    category: 'Faculty Requirements',
    title: 'Faculty Qualifications',
    description: 'Nursing faculty shall hold a current, unrestricted RN license and meet academic preparation requirements.',
    sortOrder: 18,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-D2',
    code: 'D.2',
    section: '18VAC90-27-90',
    category: 'Faculty Requirements',
    title: 'Faculty-Student Ratio',
    description: 'Programs shall maintain adequate faculty-to-student ratios for classroom and clinical instruction.',
    sortOrder: 19,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-D3',
    code: 'D.3',
    section: '18VAC90-27-90',
    category: 'Faculty Requirements',
    title: 'Professional Development',
    description: 'Faculty shall participate in ongoing professional development activities.',
    sortOrder: 20,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Program Administration (Section E)
  {
    id: 'VBON-E1',
    code: 'E.1',
    section: '18VAC90-27-80',
    category: 'Program Administration',
    title: 'Program Administrator',
    description: 'The nursing education program shall have a qualified program administrator who is responsible for program oversight.',
    sortOrder: 21,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-E2',
    code: 'E.2',
    section: '18VAC90-27-80',
    category: 'Program Administration',
    title: 'Policies & Procedures',
    description: 'Written policies and procedures shall govern program admission, progression, and graduation.',
    sortOrder: 22,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-E3',
    code: 'E.3',
    section: '18VAC90-27-80',
    category: 'Program Administration',
    title: 'Student Records',
    description: 'Program shall maintain accurate and complete student records as required by the Board.',
    sortOrder: 23,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'VBON-E4',
    code: 'E.4',
    section: '18VAC90-27-130',
    category: 'Program Administration',
    title: 'NCLEX Pass Rates',
    description: 'Program shall maintain NCLEX pass rates that meet or exceed Board requirements (80% or higher).',
    sortOrder: 24,
    isActive: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
